### ISSUE TITLE
Gibt es Tutorials auf Englisch?

### ISSUE THREAD

**Issue by richpav** [Ultraschall/ultraschall-3#17]
Ich spreche kein Deutsch. Ich wünschte, ich hätte Zeit, Deutsch zu lernen. Do any tutorials exist in English?

**Comment by heikopanjas** [comment]
Sorry, but everything we have at https://ultraschall.fm is in German. However, there is https://sendegate.de, which is a german speaking forum where people talk about technical aspects of podcasting like Podlove or Ultraschall. I don't see why you should not ask your questions there. 

We are thinking about English tutorials for ages now, but since we are just a small group of people that are doing this in our spare time, we didn't get very far. Sorry...
